/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"
/*
 * BOARD INFO :-
 *
 * USER BTN  	PA0  	,BUS - AHB1	,CLK->	AHB1EN (BIT	0)
 * GREEN LED  	PD12  	,BUS - AHB1	,CLK->	AHB1EN (BIT	3)
 * ORANGE LED  	PD13	,BUS - AHB1	,CLK->	AHB1EN (BIT	3)
 * RED LED  	PD14	,BUS - AHB1	,CLK->	AHB1EN (BIT	3)
 * BLUE LED  	PD15	,BUS - AHB1	,CLK->	AHB1EN (BIT	3)
 *
 *
 * */
#define BTN_PORT	GPIOA
#define BTN_PIN		GPIO_PIN_0
#define LED_PORT	GPIOD
#define LED_PIN		GPIO_PIN_12

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void PD12_LED_Init(void);
void PA0_BTN_Init(void);

int main(void)
{
	HAL_Init();
	// 1. CONFIGURE LED
	PD12_LED_Init();
	// 2. CONFIGURE BUTTON
	PA0_BTN_Init();

	GPIO_PinState ButtonStatus;

	while(1)
	{
		// READ FROM BUTTON
		ButtonStatus = HAL_GPIO_ReadPin(BTN_PORT,BTN_PIN);
		// WRITE TO LED
		HAL_GPIO_WritePin(LED_PORT,LED_PIN,ButtonStatus);
	}

    /* Loop forever */
	for(;;);
}


void PD12_LED_Init(void)
{
	__HAL_RCC_GPIOD_CLK_ENABLE();

	GPIO_InitTypeDef	GPIO_InitStruct = {0};
	GPIO_InitStruct.Pin		= LED_PIN;
	GPIO_InitStruct.Mode 	= GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull 	= GPIO_NOPULL;
	GPIO_InitStruct.Speed	= GPIO_SPEED_LOW;

	HAL_GPIO_Init(GPIOD,&GPIO_InitStruct);
}

void PA0_BTN_Init(void)
{
	__HAL_RCC_GPIOA_CLK_ENABLE();

	GPIO_InitTypeDef	GPIO_InitStruct = {0};
	GPIO_InitStruct.Pin		= BTN_PIN;
	GPIO_InitStruct.Mode 	= GPIO_MODE_INPUT;
	GPIO_InitStruct.Pull 	= GPIO_NOPULL;
	GPIO_InitStruct.Speed	= GPIO_SPEED_LOW;

	HAL_GPIO_Init(GPIOA,&GPIO_InitStruct);
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
